topcoat-data/topcoat-public

visualizations/big_number.html
visualizations/multi_selector.html
visualizations/search_filter.html

Refactoring and bug fixes for following visualizations.
1. multi_selector: Watchers replaced with computed properties.
2. search_filter: Text from url will also populate now.
3. big_number: Watchers replaced & logic for detecting positive or negative changes fixed.

code refacture and init fixes

---

visualizations/date_picker.html
visualizations/date_range.html

ability to format dates

---

visualizations/TTextInput.vue

Text Input imported from Expandable Modules.

Text Input component from Expandable Modules Repo

---

visualizations/frontend/filters/date_range.html

Copy code from date_picker.html file, excluding picker_mode features.

fixes for legacy date_range filter

---

library/templates/Simple/Simple.html
visualizations/frontend/filters/date_picker.html

I think some tags got mis-nested and the stricter html parser is flagging a couple things:

Tag cleanup

---

library/components/TPager.vue
library/components/TTable.vue

Big thing was removing the hack that told the back end to include the TColumnConfig component in the imports, that is now handled directly in the parser. Additionally the page variable in the TPager conflicts with a page variable added by Topcoat, so this PR renames the "page" in TPager to "internalPage"

Table v1 updates

---

.gitignore
visualizations/frontend/filters/v2/TCheckboxSwitch.vue
visualizations/frontend/filters/v2/TInput.vue
visualizations/frontend/filters/v2/TMultipleValueInput.vue
visualizations/frontend/filters/v2/TSelect.vue

This PR adds various default input components from ProductCL repo and adds support for helper functions as well.

ProductCL Components

---

visualizations/frontend/filters/v2/TCheckboxGroup.vue
visualizations/frontend/filters/v2/TMultipleValueInput.vue
visualizations/frontend/filters/v2/TSelect.vue

Various fixes for selectors and other components.

Component Fixes

---

library/components/TDropdown.vue
library/components/TExpandable.vue
library/components/TFilterGroup.vue
library/components/TNavigationDropdown.vue
visualizations/frontend/filters/v2/TMultiSelector.vue
visualizations/frontend/filters/v2/TSelect.vue
visualizations/frontend/filters/v2/TTags.vue

1. Multi selector, switch between dropdown or inline.
2. Multi selector, select/unselect all feature.
3. Dropdown, new slot to show items outside popup.
4. Filter Group, handle max height and width.
5. Tags component supports is-searchable prop to enable search.
6. Highlight active filters inside t-filter-group.

General fixes

---

library/components/TFilterGroup.vue
visualizations/frontend/filters/v2/TTags.vue
visualizations/frontend/other/TBigNumber.vue

1. `t-filter-group`: watch for url changes to decide active or inactive filters.
2. `t-tags`: skip empty values.
3. `t-big-number`: large number overflow fix

General component fixes

---

library/components/TUrl.vue

The insights table should open info on specific issues in a new tab, added a prop to support that to the TUrl component.

Add :openInNewTab" prop to the TUrl component

---

visualizations/frontend/other/TFilterValues.vue
visualizations/frontend/other/TTagFilterValues.vue

Added a new prop for both filter value components to handle a non t-layer way to get values from url, this is good in cases where ids in url are same as label.

handle non t-layer filter values

---

library/components/TDropdown.vue
library/components/TExpandable.vue
library/components/TFilterGroup.vue
library/components/TNavigationDropdown.vue
library/components/TUrl.vue
library/components/tableComponents/OpenOrFixed.vue
visualizations/frontend/filters/TVisGrouper.vue
visualizations/frontend/filters/v2/TCalendarPicker.vue
visualizations/frontend/filters/v2/TMultiSelector.vue
visualizations/frontend/filters/v2/TSelect.vue
visualizations/frontend/filters/v2/TTags.vue
visualizations/frontend/other/TBigNumber.vue

Related PR: https://github.com/snyk/topcoat-core/pull/469

feat: Adapt code to new architecture

---

library/components/TDropdown.vue

Related ticket: https://snyksec.atlassian.net/browse/DP-309
Related PR: https://github.com/snyk/topcoat-core/pull/491
GIF showing working dropdown:

fix: Use vueuse/onClickOutside to handle dropdown open/close

---

visualizations/frontend/other/TTable.vue

To test check out the add_issues_details_no_data branch, in the issues details page select filters until there are no matching issues and instead of "no data" you should see table contents that match [this](https://www.figma.com/file/IaywW74sLSgYJSYHjOC0ZL/Reporting-Beta-2022?node-id=2882%3A47764).

added no_data slot to TTable

---

visualizations/frontend/filters/v2/TDatePicker.vue

Jira [Ticket](https://snyksec.atlassian.net/jira/software/c/projects/DP/boards/443?modal=detail&selectedIssue=DP-357&search=date&assignee=62261dde94f7e200690091ae)

include today's date in date picker

---

library/components/TPdf.vue
visualizations/frontend/filters/v2/TRangeInput.vue

**Problem**
This component gives users the ability to drag the slider and update the value, which can cause too many request on every change and fills up out tracking data as well.
**Fix**
Added throttling to only update after half second after user stops dragging slider.

Range Input throttle

---

visualizations/frontend/other/TBigNumber.vue

New big number was developed in rush with many ideas that make it too complex, this PR aims to clean it a bit and also fix several issues.
It also solves this [jira](https://snyksec.atlassian.net/jira/software/c/projects/DP/boards/443?modal=detail&selectedIssue=DP-325&assignee=62261dde94f7e200690091ae) ticket as well.
The tooltip part for big number in this PR depends on this [PR](https://github.com/topcoat-data/topcoat-public/pull/121).

various big number fixes

---

library/components/TPdf.vue

This PR has changes to allow new tooltip function.
Tooltip [PR](https://github.com/topcoat-data/topcoat-public/pull/133)

Refactor pdf tooltip code.

---

library/components/TDropdown.vue
library/components/TFilterGroup.vue

This fixes some warnings in the dev tools that impede local development. Currently we have many warnings when developing locally and it is hard to see what is really important and what is just a warning from a component. 
I deliberately left in the formatting changes, and have pointed out the exact changes for ease of reviewing. 
project.state.warnings includes many warning. In this PR I am fixing only the first one related to `outsideElementClasses`
```
[
"TOPCOAT WARNING: Invalid default value for prop \"outsideElementClasses\": Props with type Object/Array must use a factory function to return the default value.",
"TOPCOAT WARNING: The data property \"width\" is already declared as a prop. Use prop default value instead.",
"TOPCOAT WARNING: Invalid prop: type check failed for prop …
```

chore: fix warning - turn array default into function for `outsideElementClasses` prop

---

library/components/TCsvExport.vue

Jira Ticket: https://snyksec.atlassian.net/browse/DP-382?atlOrigin=eyJpIjoiYzIyZWYyM2M3Yjc3NGFlZTllYzNlZTNkNDlkNzJmNDUiLCJwIjoiaiJ9

chore: use button instead of BaseButton

---

library/components/TPdf.vue

This PR will add following.
1. Format the code pdf component.
2. Add support for pdf layout options as a prop.
Backend [PR](https://github.com/snyk/topcoat-core/pull/514)

add options prop to pdf exporter

---

library/components/TPdf.vue
library/components/TTooltip.vue

Tooltip has multiple behavioural issues when it comes to conditionals and placements.
**Issues Fixes:**
1. Fails to place itself according to width and height of trigger until mouse moves again.
2. Can't keep open for user to click a link inside tooltip.
Jira [ticket](https://snyksec.atlassian.net/jira/software/c/projects/DP/boards/443?modal=detail&selectedIssue=DP-377&assignee=62261dde94f7e200690091ae)
One example with PDF component.
**Before**
**After**

correction in tooltip placement logic

---

visualizations/frontend/filters/v2/TMultiSelector.vue

Use the new component added in: https://github.com/snyk/topcoat-core/pull/516 to support big data sets.
This changes is being applied only to the `TMultiSelector` component but it should be easy to adapt it to other if needed.
Use the new added method `getColumnsByNameAndAttribute` in the PR mentioned above to avoid looping twice over the whole `rows` data set.
Fixed some UI layout issues.
Related JIRA ticket: https://snyksec.atlassian.net/browse/DP-271?atlOrigin=eyJpIjoiOGVjMWFjNDAzNzhhNGYzM2E0NGJmZjc0MDYwNDFmOGEiLCJwIjoiaiJ9

fix: Add virtualization to TMultiSelector

---

visualizations/frontend/filters/v2/TDatePicker.vue

Issue [ticket](https://snyksec.atlassian.net/jira/software/c/projects/DP/boards/443?modal=detail&selectedIssue=DP-388&assignee=62261dde94f7e200690091ae)
**How to test**
- Switch the modules branch inside IDE to `fix/handle-relative-dates` and click build modules.
- Select a non-custom preset, click apply, then change the url dates manually and refresh the page, it should not matter what manual date was changed in URL, it should resort back to what preset has calculated the date to be.
- Custom date should be modifiable will stay absolute.
Linked snyk-insights [PR](https://github.com/snyk/snyk-insights-topcoat/pull/43)

handle relative dates

---

library/components/TUrlCopyButton.vue

This PR will add support for `context[parent]` inside url copy component.
**How to test**
1. Switch to this branch inside IDE.
2. Build modules.
3. Go to executive page and click Copy URL button.
**Expected results**
1. If opened inside snyk website, the url matches with app.snyk.io
2. If opened outisde snyk website, the url matches with current url.
3. Also copies all filters.

Handle parent context for copying url.

---

visualizations/frontend/filters/v2/TDatePicker.vue

Added clear button to date picker button when a preset is selected, just like absolute dates (not part of design).

add clear button to relative date picker

---

visualizations/frontend/other/TTable.vue

This is all @icoconutgirl 
This PR makes some fixes for the table design as per the following Jira ticket
Jira ticket: https://snyksec.atlassian.net/browse/DP-399
The grouped table is being used in the Vulnerability Report
* Switch the Git branch in https://snyk-insights.topcoatdata.app/a/develop to point to `feat/vulnerability`
* change the https://snyk-insights.topcoatdata.app/a/develop/project/config|yml] to point to `chore/table-updates`
```
modules:
revision: chore/table-updates
```
* rebuild modules, by clicking the cloud icon.
* Go to https://snyk-insights.topcoatdata.app/vuln-detail You should see the grouped table there.

Table updates for Grouped issues table

---

visualizations/frontend/filters/v2/TTagsInput.vue

**Problem**
Tags filter uses `value_key` format for URL which can easily break with a sql layer returns `_` inside it's key and value names (value_1_key_1).
**Solution**
Replace the hacky pair system to use stringified objects in URL for easy parsing.

Key value pair format change

---

visualizations/frontend/filters/v2/TTagsInput.vue

Unset tags filter when no object string in URL.

handle empty tags object

---

.npmrc
package-lock.json
package.json

This PR will force node version from APP UI's package.json.

pin node version

---

visualizations/frontend/filters/v2/TDatePicker.vue

This PR will adds new preset for date range picker.
- Last 365 Days
[JIRA](https://snyksec.atlassian.net/browse/DP-546?focusedCommentId=596164&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-596164)

two new presets for date filter

---

library/components/TFiltersSection.vue
visualizations/frontend/filters/TTagsSelector.vue
visualizations/frontend/filters/v2/TMultiSelector.vue

This PR has minor syntax changes and refactoring for several filter ux components.
1. TFiltersSection: Remove un-used functions.
2. TMultiSelector: Ability to see selected items only.
3. TTagsSelector: Text change.

General fixes for Filter UX components

---

library/components/tableComponents/SnykPager.vue

This address Jira ticket: https://snyksec.atlassian.net/browse/DP-482

Added .toLocaleString() when displaying the total number of items

---

visualizations/frontend/other/TCustomHtml.vue

Custom html component
**Syntax**
```
<t-custom-html t-layer="value_filter_layer_type">
{{value_filter_layer_type}}
</t-custom-html>
```
Here the layer name `value_filter_layer_type` contains the raw data of the visualization variable `rows`.
[Backend PR](https://github.com/snyk/topcoat-core/pull/576)

TCustomHtml component

---

library/components/TFiltersDropdown.vue

**Issue**  
Users deleting the previous text present in search input and then searching for another filter.
**Solution**  
Added autofocus and pre text selection for search input.

Add autofocus and text selection

---

visualizations/frontend/charts/pie_chart.html

Modify code for pie and donut charts.

Modify pie chart

---

visualizations/frontend/charts/bar_chart.html

Modify bar chart

---

visualizations/frontend/charts/line_chart.html

_This PR modify some existing code and make line chart customization easy for ongoing and future projects_
_To test, this requires updates in both topcoat-public and topcoat-reports so check out the 'feat/line-chart' topcoat-reports branch and run a build and sync modules._

Modify line chart

---

visualizations/frontend/charts/pie_chart.html

_Modify hovermode and add showlegend_
_To test, this requires updates in both topcoat-public and topcoat-reports so check out the 'feat/owasp-top-10' branch of  topcoat-reports repo and run a build and sync modules._

Add hovermode & showlegend

---

library/components/TCsvExport.vue
library/components/TFilterGroup.vue
library/components/TFiltersSection.vue
library/components/TUrl.vue
library/components/TUrlCopyButton.vue
visualizations/frontend/filters/TRangeSelector.vue
visualizations/frontend/filters/TTagsSelector.vue
visualizations/frontend/filters/TTextInput.vue
visualizations/frontend/filters/date_picker.html
visualizations/frontend/filters/date_range.html
visualizations/frontend/filters/date_range_simple.html
visualizations/frontend/filters/multi_selector.html
visualizations/frontend/filters/search_filter.html
visualizations/frontend/filters/select_filter.html
visualizations/frontend/filters/table_search.html
visualizations/frontend/filters/toggle.html
visualizations/frontend/filters/v2/TCalendarPicker.vue
visualizations/frontend/filters/v2/TCheckboxSwitch.vue
visualizations/frontend/filters/v2/TInput.vue
visualizations/frontend/filters/v2/TMultiSelector.vue
visualizations/frontend/filters/v2/TMultipleValueInput.vue
visualizations/frontend/filters/v2/TRangeInput.vue
visualizations/frontend/filters/v2/TRangeSlider.vue
visualizations/frontend/filters/v2/TSearchInput.vue
visualizations/frontend/filters/v2/TSelect.vue
visualizations/frontend/filters/v2/TTags.vue
visualizations/frontend/other/TSelectColumns.vue
visualizations/frontend/other/TTable.vue

This reverts commit fac876833163f0daa3700f324739ca918bbd8e38.
_Explain why this PR exists_

Revert "Feat/add remove all filters (#190)"

---

library/components/TCsvExport.vue

Fixes csv export error.
Switch to this public branch inside IDE to test.

error fix for csv export component

---

visualizations/frontend/other/TBigNumber.vue

_Add an if condition to big number label and a slot to show some extra content in the footer_
_To test this, checkout to feat/enterprise_reporting branch of topcoat-reports repo_
- Link to Jira Ticket: https://snyksec.atlassian.net/jira/software/c/projects/DP/boards/443?modal=detail&selectedIssue=DP-955&assignee=62261de3302c6b006af498c3

Add a condition and slot

---

visualizations/frontend/charts/bar_chart.html
visualizations/frontend/charts/bubble_chart.html
visualizations/frontend/charts/choropleth.html
visualizations/frontend/charts/donut_chart.html
visualizations/frontend/charts/line_chart.html
visualizations/frontend/charts/pie_chart.html
visualizations/frontend/charts/scatter_plot.html

Height prop added for plotly viz files.
Backend [PR](https://github.com/snyk/topcoat-core/pull/682)

height prop for ploty viz files

---

visualizations/frontend/charts/line_chart.html

_Modify mode and marker size _
_To test this, checkout to feat/enterprise_reporting branch of topcoat-reports repo and build & sync the modules_
- [Link to Jira ticket](https://snyksec.atlassian.net/jira/software/c/projects/DP/boards/443?modal=detail&selectedIssue=DP-957&assignee=62261de3302c6b006af498c3)

Modify mode and marker size

---

library/components/TPdf.vue

_Add a new slot for icon_
_To test this, checkout to feat/enterprise_reporting branch of topcoat-reports repo and build and sync modules. 
- Link to Jira ticket: https://snyksec.atlassian.net/browse/TEAM-0000

Add icon slot

---

library/components/TPdf.vue

_Remove extra padding from left_

Remove padding from left

---

library/components/TPdf.vue

_Remove padding & modify font weight_

Remove padding & modify font weight

---

visualizations/frontend/charts/bar_chart.html
visualizations/frontend/charts/bubble_chart.html
visualizations/frontend/charts/choropleth.html
visualizations/frontend/charts/donut_chart.html
visualizations/frontend/charts/pie_chart.html
visualizations/frontend/charts/scatter_plot.html

_Add  border overwrite to Plotly charts_

Add border overwrite to charts

---

library/components/tableComponents/SnykPager.vue
visualizations/frontend/other/TTable.vue

We are making all tables across all reports look the same. Please see linear ticket for design files.
1. Updates the border styles of the table to match the Figma Design
2. Remove `extraClass` prop
3. Add a prop `isBorderless`, 
4. Refactor position of the `SnykPager` to within the table's border
Changes that will affect usage:
| prop name | status | purpose |
|--------|--------|--------|
| extraClass | removed | to style the border of the table
| isBorderless | added | default = false. Use case: tables nested tables in expandable sections. Cases where no border is desired. 
This PR does NOT address the padding on either side of a column. In an effort to keep the changes small and shippable, I am putting this into review now. We can keep working on the rest of the design parity.
Go to …

feat: align tables styles

---

visualizations/frontend/other/TBigNumber.vue

Prevent access to rows when they are null

fix: prevent null row to be access

---

library/components/tableComponents/SnykPager.vue
visualizations/frontend/other/TTable.vue

This PR follows up on #239 
1. Fix: Stop Pagination scrolling with a table. 
2. Fix: Add cursor to Sort icons to show user they are clickable: https://snyk.slack.com/archives/C04FDUS3KAA/p1684145532477479
3. Feat: match the design where the borders of each row do not reach the sides.
* tables with expandable sections still reach the edge
* Try replicating the 'bugs' in the Before screenshots using the 'main' branch of topcoat-public.
* Replace the branch name for topcoat-public components in `config.yml` with `feat/align-table-styles`
* Click "Rebuild and Sync modules"
* Check against the After screenshots and generally look for UI bugs.
* Check the designs to see if it is matching as much as possible
You will need to …

chore: make it so the line of table rows don't reach the edge 💅 

---

visualizations/frontend/other/TTable.vue

Without this, the no data message gets compressed into a single 2em column. For the use cases I've seen, this would improve the no data message display for any table that uses the expandable rows variant.
**Before:**
**After:**

chore: Check for table rows before applying template columns

---

visualizations/frontend/other/TTable.vue

The table cell's vertical alignment was off as reported in the linked Linear ticket (see below)
This addresses the alignment problem. 
To test this component:
* Go to the `config.yml` file and replace the branch for topcoat-public with this branch name: 
```
modules:
revision: fix/table-cell-alignment
```
* Save the changes to the config.yml file and click `Build and Sync Modules` (the cloud icon) in the left hand menu
* Check that alignment has improved on tables with sparklines, and that tables in other reports are unaffected.
- [[Jira ticket](https://snyksec.atlassian.net/browse/TEAM-0000)
](https://linear.app/snyk/issue/FP-1104/table-row-vertical-alignment-off)

fix: align content in a table cell vertically

---

visualizations/frontend/other/TBigNumber.vue

Creates a new slot next to the formatted number to enable new layouts.
- Use this branch on `snyk-insights`: `fix/analytics-layout`. It already contains these changes on it and a modified version of the Enterprise Analytics that uses the new layout.
|Before|After|
|---|---|
|<img width="661" alt="image" src="https://github.com/topcoat-data/topcoat-public/assets/1915140/924a3e02-4d16-43a4-adf8-65c64903fa81">|<img width="765" alt="image" src="https://github.com/topcoat-data/topcoat-public/assets/1915140/e6315acb-8f63-4fc9-8cec-e8005479a02f">|

fix: Add right-side slot

---

library/components/TRelativeDate.vue

fix: modify relative date component

---

library/components/TPdf.vue

New prop added to display a custom error message on PDF download fail.

error message prop added

---

visualizations/frontend/other/TTable.vue

_Set padding on tableHeaderContainer_
- [Slack thread](https://snyk.slack.com/archives/C057M221V96/p1695287111253209)
- [Jira ticket](https://snyksec.atlassian.net/browse/DP-1402)
_Current Output_
_Expected Output_

Fix padding for tableHeaderContainer

---

visualizations/frontend/filters/TTagsSelector.vue

Adds virtualization to the TTagsSelector to have similar behavior that TMultiSelector.
Before:
https://github.com/topcoat-data/topcoat-public/assets/1915140/fe5772cf-9654-4cda-9dc1-8a8325108332
After:
https://github.com/topcoat-data/topcoat-public/assets/1915140/638a2b7d-c4f1-4714-82c3-70d75c097bf2

fix: TTagsSelector to use virtual list

---

visualizations/frontend/filters/v2/TMultiSelector.vue

This reverts commit 0f51bc50db3c0ab5b921c74160bb351bcf737b11.
I found an issue on Insights' reports. Reverting before it propagates to all environments.

Revert "fix: TMultiSelector filters as array (#274) (#276)"

---

visualizations/frontend/filters/v2/TMultiSelector.vue

Fixes selectAll functionality after filter changes and some refactoring broke it.
https://github.com/topcoat-data/topcoat-public/assets/1915140/6ceacbc5-f364-4fbb-af9f-7859adb8bb70

fix: TMultiSelector selectAll
