topcoat-data/topcoat-public

visualizations/frontend/filters/v2/TCalendarPicker.vue

**Why**
The legacy date filter relies heavily on `:root` variables in every template file, which will cause confusion to new users and that old style also does not match with Product CL and sometimes appears broken (depending on primary/secondary color values of `:root`).
**New**
Because currently we do not have a calendar range picker inside Product CL, I have made added a new Date picker (should become the new default), that supports tag inversion syntax.
The calendar part is still old from ant-design but dropdown, buttons and overall styling is taken from product cl inputs.
**Syntax with all props**
```
<t-calendar-picker
t-filter:start_date="start"
t-filter:end_date="end"
t-filter:date_preset="preset"
t-filter:date="single_date"
t-layer="date_filter"
:single-picker="false" …
```

Calendar/Date Picker V2

---

visualizations/frontend/filters/v2/TSelect.vue

1. More padding near icons
2. `is-unselectable` prop for `t-select` to unselect items and skip using first value as selected on page load.

Component Issues

---

visualizations/frontend/filters/v2/TMultiSelector.vue
visualizations/frontend/filters/v2/TSelect.vue

We can use `default-value` as a `string` in `<t-multi-selector>` and `<t-select>` to set the value and its corresponding filter state in the URL.
Example:
```html
<t-multi-selector is-expanded default-value="False" t-layer="filter_ignored" t-filter:selected_items="ignored" item-label="Currently Ignored" />
```
```html
<t-select default-value="Severity" t-layer="filter_layer_type" t-filter:dropdown="issue_by" label="Issues By" item-label="Issues_by" />
```

feat: Adding support for default-value in TSelect and TMultiSelector

---

visualizations/frontend/filters/v2/TMultiSelector.vue

Use `value` instead of `rendered` attribute for `ids`.
Results comes with two attributes: rendered and value.
`value` is the raw value
`rendered` is a formatted version of the `value`.
Examples:
Related PR: https://github.com/snyk/topcoat-core/pull/487

fix: Use value for getColumn ids

---

library/components/TDropdown.vue
library/components/TExpandable.vue
library/templates/Report/ReportHeader.vue
visualizations/frontend/filters/v2/TMultiSelector.vue
visualizations/frontend/filters/v2/TTagsInput.vue

What's new
- Tags filter from Product CL.
Fixes:
- Some product CL filters do not work well with `v-show` or `v-if` when used inside a dropdown, used `height: 0px` logic for them instead, which is working great.
- Removed un-used code.
Tags Syntax:
```
<t-tags-input
t-layer="filter_cve"
item-label="CVE"
t-filter:selected_items="cve"
:is-label-capitalized="true"
:is-single-tag="true" // If only one tag, use this.
/> 
```

Tags filter and fixes

---

visualizations/frontend/other/TTable.vue

Bug: https://snyksec.atlassian.net/browse/DP-241
Note: there were actually 2 distinct issues:
1.  When filters reduce the total # of rows to 0 the spinner kept spinning, the currently shown rows stayed visible, and the "no data" message did not appear
2. When the url filters resulted in no rows when the page is loaded the table didn't show up at all.
This PR addressed both.

Fixed the "no data" message not showing up when filters reduced the # of matching rows to 0

---

visualizations/frontend/other/TTable.vue

Firefox does not support dates in the format month-day-year, fortunately the back end properly converts that to an iso compatible date in the "value" property. Unfortunately, that value was not available to t-columns, so this adds the "value" to as a slot prop so t-colum
ns can reference it.

Add the "rendered" slot prop and updated the "value" slot prop to return the "value" property from the cell object

---

visualizations/frontend/other/TTable.vue

We have been intending to add the horizontal scroll on the table for a while. This is the most basic implementation of that, so that tables with lots of columns aren't squished, or overflowing their container.

feat: add horizontal scroll on table

---

visualizations/frontend/other/TTable.vue

To test it is easiest to see the spinner when topcoat-core has been restarted so the data isn't cached.
Previous behavior: there was a vertical scrollbar on the table and the spinner was cut off.
Current behavior: The table is the correct height to show the spinner entirely without a vertical scrollbar.

Fixed the vertical scroll when data is loading in a table and the spinner is showing

---

library/components/TUrl.vue

To test: 
1. check out the "TURL_testing" branch of snyk-insights
2. click the "Build and Sync modules" icon (cloud between the + and refresh icons)
3. Open: http://localhost:2525/executive_summary?ignored=False&project_name=19377273%257C23023122%257C19174048
4.  Verify that the table at the bottom has 3 rows in the "juice-shop" row, click on the "Open Issues" column.
5.  Verify that the URL in the newly opened tab has the parameter "project_name=19377273", without any additional project ID's
6. Also verify that the styling of the cells in the OPEN ISSUES column is not blue and does not have an underline.

Added prop to use/not use the default url styling and made the additionalUrlParams override the page filters when they include the same parameter

---

library/components/TUrl.vue

To test:
- check out the executive_summary branch of snyk-insights. 
- Open the [executive summary](http://localhost:2525/executive_summary?context%5Borg%5D=4a3d29ab-6612-481b-83f2-aea6cf421ea5&ignored=False&exec_summary_start_date=2022-05-01&exec_summary_end_date=2022-05-31)
- click the "Total Identified" big number
- verify that the url includes the param "context%5Borg%5D=4a3d29ab-6612-481b-83f2-aea6cf421ea5"

Added includeContextParam prop to TURL

---

visualizations/frontend/filters/v2/TDatePicker.vue

Adds new props for date picker.
1. `default-date-preset`: Will apply the preset and dates accordingly, can accept both `key` and `label`.
2. `default-start-date`: Will apply the date as start date, also respects `mode(range, single)` .
3. `default-end-date`: If empty but start date has default, then same is applied to this one to avoid any glitch.
Note:
- If default preset given then start and end date defaults are skipped.
- Using default dates will automatically set preset to custom (if preset default not used).

Default value props for date picker

---

library/components/TPdf.vue
library/components/TTooltip.vue
library/components/TUrlCopyButton.vue

Fixes:
1. Current tooltip was having trouble placing it self near it's trigger and needed a better approach
2. is-clickable prop can be used to make tooltip appear on click
3. outside click detection function is used to close tooltips
4. t-pdf and t-url-copy-button are now using this new verison as well.
How to test:
1. Switch your config.yml `revision` to this branch.
2. Click Build button inside IDE.
3. Clicking on pdf download will open the new tooltip.
4. Hovering on t-url-copy-button will open the tooltip.
New syntax:
```
<t-tooltip width="200px" position="top" :is-clickable="false">
<button slot="trigger">button</button>
This is the tooltip text, now also supports anchor tags.
</t-tooltip>
```

refactor tooltip code

---

visualizations/frontend/other/TBigNumber.vue

To test, check out the [executive_summary_blue_clickable_big_numbers](https://github.com/snyk/snyk-insights-topcoat/tree/executive_summary_blue_clickable_big_numbers) branch and open the following page: http://localhost:2525/executive_summary?context%5Borg%5D=4c62f811-1816-4896-a91d-22577bb8eaca&ignored=False&exec_summary_end=2022-08-31&exec_summary_start=2022-04-01
This change is in response to [this slack discussion](https://snyk.slack.com/archives/C03UN2ECN3B/p1661890523584819).

Added "numberTextColor" to TBigNumber

---

library/templates/Report/Report.vue

Get rid of that bottom padding that is producing a gap at the bottom of the table:

fix: Remove bottom padding from Report component

---

library/components/TUrl.vue

Goal: remove the underlines from links, per conversation with @gau94rav 
To test: in snyk-insights check out the "remove_link_underline" branch and sync modules, then open the issue details page and verify that all the links are no longer underlined.

remove underline from links

---

visualizations/frontend/other/TTable.vue

Goal: add a tooltip prop to the table that will add the tooltip icon + text next to the title.
To test, check out add_tooltip_prop_to_table branch in snyk-insights, sync modules, and open the issue details page.

Add tooltip prop to table

---

visualizations/frontend/other/TTable.vue

Goal: provide server-side sorting that is done in the sql to the table.
To test:
1. In  snyk-insights, check out the "server_sort" branch and run "build and sync modules"
2. Open snyk-insights in the [iFrame](https://app.snyk.io/group/5ea22317-e879-4eb9-8ef7-411dc7c3a604/reporting?context%5Bpage%5D=issues-detail&issue_status=Open&issue_by=Severity)
3. Verify that the table starts sorted by "SCORE" descending, "ISSUE" ascending, and that the "PRODUCT" column is sortable but not currently sorted.
4. Click the up/down/up-down icons to sort by columns
5. Open the URL in a new tab and verify that the updated sorting is preserved- not just which columns are sorted, but also the order in which they are sorted
6. Export a pdf and verify that the sorted table in the pdf matches the page
7. Export …

Server side sorting implementation

---

visualizations/frontend/other/TSelectColumns.vue
visualizations/frontend/other/TTable.vue

Goal:
Allow users to show/hide columns on the fly. This includes updating the columns shown in pdf and csv exports in addition to what appears in the table.
To test:
Note: The ISSUE_SEVERITY and ISSUE columns cannot be hidden and will always be present. Because the ISSUE columns depends on multiple layer columns, all of those layer columns will end up in the csv export.
1. Check out the modify_columns branch in snyk-insights
2. sync modules
3. in the iframe, open the issue details page
4. Verify that the following columns are present: 
5. Select/Deselect columns
6. Verify that the selected/deselect columns are added/removed from the table as appropriate.
7. Refresh the page
8. Verify that the columns you selected/deselected are still present/absent as appropriate
9. Export a pdf, verify …

Fix modify columns

---

visualizations/frontend/filters/v2/TDatePicker.vue

When a preset is selected instead of custom absolute date, show that selected preset as filter label.
[Design](https://www.figma.com/file/IaywW74sLSgYJSYHjOC0ZL/Reporting-Beta-2022)

show relative preset on date button if selected

---

visualizations/frontend/other/TSelectColumns.vue

Goal: Make the "reset" button in modify columns reset to the default visible columns, not just the columns that cannot be hidden.
To test:
1. Check out the "modify_columns_updates" branch in snyk-insights
2. syn modules
3. open issue details page
4. select and deselect columns
5. in modify columns, click the "Select All"
6. in modify columns, click "reset"
7. verify that the following columns are visible after the reset:
SCORE
ISSUE
CVE
CWE
PROJECT
EXPLOIT MATURITY
AUTO FIXABLE
INTRODUCED
PRODUCT
Notes: It would be much better to remove the filter entirely, unfortunately due to the limitation where visualizations cannot be nested TSelectColumns does not have access to the functions that handle that and this is simpler than adding a reset event or reinventing the wheel.

Fix reset button in modify columns

---

visualizations/frontend/other/TTable.vue

This PR adds a background color to rows on a table with the `canCollapseDetailRows` prop set. It also makes a few updates to the toggle to bring it close to the design, and also add a background colour to it.
The grouped table is being used in the Vulnerability Report
Go to 
* Switch the Git branch in https://snyk-insights.topcoatdata.app/a/develop to point to `feat/vulnerability` 
* change the https://snyk-insights.topcoatdata.app/a/develop/project/config|yml to point to `chore/update-collapsible-row-color` for topcoat-public
```
modules:
revision: chore/update-collapsible-row-color
```
* rebuild modules, by clicking the cloud icon.
* Go to https://snyk-insights.topcoatdata.app/vuln-detail
* You should see the grouped table there. …

chore: add gray background to rows that can expand

---

visualizations/frontend/other/TTable.vue

Goal: Allow users to exclude a column from sorting.
To test:
1. In snyk-insights, check out the implement_sort branch
2. sync modules
3. open the Issues Detail page
4. Verify that the first column with the severity icon and no header is not sortable.

Added excludeFromSort table prop

---

visualizations/frontend/other/TTable.vue

To test, check out the implement_sort branch in snyk-insights.
Please verify that not only does the sorting persist when both reloading the page and copy-pasting the URL, but also that it works with modified columns and preserves the order in which the columns were sorted.
Additionally I should have created a separate PR for this, but this also fixes an issue where the fix to get the tooltip to not be cut off by the table div was making the contents overflow when a bunch of columns are shown.  So please also verify that the table scrolls properly when all modifiable columns are selected and that the tooltip (see the issues summary page for one) is visible.

Fix sort url

---

visualizations/frontend/other/TTable.vue

Quick updates to the header cell font size, sorting icon colors, and update sorting icons to triangles instead of chevrons. To test, update the modules branch to table_design_fixes, the headers should have a 12px font size, the sorting icons should be #323232, and the unsorted icon should have opacity .5.

Table design fixes

---

visualizations/frontend/filters/v2/TMultiSelector.vue

This PR fixes 2 problems.
1. Returning `null` rows is possible by some layers, which breaks multi selector when using `is-searchable` prop.
2. Reset selected button was not working.

handle null rows for multi selector

---

visualizations/frontend/other/TTable.vue

I don't think this is hugely significant, but this error show up in the console when rendering the pdf template, for example
https://dave.topcoatdev.net/reporting/issues-detail/pdf?issue_status=Open
```
TypeError: this.pagerResetFunction is not a function
at o.onVisualizationUpdated (pdf?issue_status=Open&issue_by=Severity&table_issues_detail_cols=SCORE%7CCVE%7CCWE%7CPROJECT%7CEXPLOIT+MATURITY%7CAUTO+FIXABLE%7CINTRODUCED%7CSNYK+PRODUCT:1927:12)
at o.loading (core.4c21d8d71bc715e36d64.js:2:3463150)
at qe (core.4c21d8d71bc715e36d64.js:2:2943436)
at xn.run (core.4c21d8d71bc715e36d64.js:2:2959950)
at bn (core.4c21d8d71bc715e36d64.js:2:2957921)
at Array.<anonymous> (core.4c21d8d71bc715e36d64.js:2:2944522)
at et (core.4c21d8d71bc715e36d64.js:2:2943921)
```

Don't reset pager if it doesn't exist

---

library/components/TFiltersSection.vue

**What's added**
A default filter slot for filter section.
**Reason**
A default filter does not have to go through the initialisation process as it is always visible, adding any filter to this slot will remove it from dropdown's init logic.
**Usage**
```
<t-filters-section>
<t-select slot="defaultFilter" />
// This filter will be removed from dropdown's init logic and will be directly displayed on page.
</t-filters-section>
```

add default filter slot to filter section

---

library/components/TNavigationDropdown.vue
visualizations/frontend/filters/TTagsSelector.vue
visualizations/frontend/filters/v2/TMultiSelector.vue
visualizations/frontend/filters/v2/TSelect.vue

Fixes for selectors
1. Search input css broken.
**Before**
**After**
2. Label fix for t-select.
3. Remove `setFilter` function call as it was resulting in iframe not upadting.
Backend [PR](https://github.com/snyk/topcoat-core/pull/541) for issue number 3.

Filters css and other fixes

---

visualizations/frontend/filters/TTagsSelector.vue
visualizations/frontend/filters/v2/TMultiSelector.vue

**Problem**
Currently a filter with many selected values can go out of div bouns.
**Solution**
Added a new prop called `selectedVisibleCount` that shows 5 items by default and can be customized.
[Figma](https://www.figma.com/file/1Yt1eSMomCATi3wBUeG5tr/Patch-ProductUI?node-id=10233%3A123753&t=hwTO67gRaXSBqvUZ-4)

add visible item count and limit for multi and tags selectors

---

library/components/TDropdown.vue
library/components/TFiltersSection.vue

This PR adds following changes.
1. Show delete icon inside filters.
2. Fix hover color for add filter button.
Note: Due to programmatic slot manipulation with filter section, using a third party icon directly does not work at this point, so direct SVG code is being used.
[Figma](https://www.figma.com/file/IaywW74sLSgYJSYHjOC0ZL/Reporting-Beta-2022?node-id=5133%3A84594&t=nHWDZSuSjPJ5Juu3-4)

Add delete icon to filters, fix hover border color

---

visualizations/frontend/filters/TRangeSelector.vue

This PR adds some changes to the UI of range selector.
What's new
- Inputs can now be used to modify range values
- Min and max values are now shown inside UI.
- Validation for min/max values.

upgrade range selector

---

library/components/tableComponents/IssueSeverityIcon.vue

To test, check out the feat/severity-sorting branch and update config.yml to use this branch. Sorting by the severity in the issues-detail table should now respect the actual severity, not the alphabetical order of Critical, High, Low, and Medium.

Add support for numerical issue severities

---

library/components/TUrl.vue

Allows for the TUrl component to handle relative (without scheme, host or port) by using the origin as a base url.
Absolute urls continue to work as before.

Support relative urls with base url as window location

---

visualizations/frontend/filters/TTagsSelector.vue

Goal: Allow users to search for text in related fields to a filter. For example, as user may not remember "CWE-502"  but does remember "Deserialization of Untrusted Data", so even though "Deserialization of Untrusted Data" is not shown to the user as part of the filter dropdown, allow users to search for it and it should match "CWE-502"  
To test:
- check out the meg-dev branch in the builder, then run a sync and build.
- Open issues details and select the cve filter
- In the search bar of the filter, verify that filtering the CVEs by their display values works as expected
- Verify that 'SQL Injection' returns all the CVEs, but that ''SQL Injection**s**' return none
- Verify that 'Use of Hard-coded Credentials' returns no CVEs
- Remove ' :searchFields="['TITLE']" ' from the issue details …

Feat/add general search to TTagsSelector

---

library/components/Tile.vue
visualizations/frontend/other/TTable.vue

Remove references to the iframe property that was part of embeds. It's not defined anymore.

Remove legacy embed iframe references

---

visualizations/frontend/filters/TRangeSelector.vue

**Bug**
Close (X) icon inside priority score filter was doing nothing. 
**Solution**
Now this icon resets the filter to it's initial state.

Fix priority score reset icon

---

library/components/TNavigationDropdown.vue

**Problems**
- When opening a new tab from navigation dropdown inside iframe, the main URL gets used which results in redirected page to load outside of iframe.
**Fixes**

iframe fix for navigation

---

visualizations/frontend/filters/TTagsSelector.vue

Goal: Avoid race condition when fetching data where the filters have been updated but a previous result set is returned after the result for the latest severity filter change so data that does not match the selected filters is displayed to users.
To test:
- update the revision in config.yml to 'chore/add_debounce_to_TTagsSelector'
- sync and build modules
- open Issues Detail and add the severity filter
- rapidly select and deselect options and verify that the data is only fetched when there is a pause between updating the selections (the loading circles will appear when data is being fetched) and that the data stays in sync with the filters.

Added debounce to TTagsSelector

---

visualizations/frontend/other/TTable.vue

Mehak needs a way to style the first row in table, this addresses that need in a general way. 
To test:
- update revision in config.yml to "chore/add_first_and_last_row_css_classes_to_table"
- build and sync
- add ":cellCssFunction="(column, columnIndex, row, rowIndex) => { if (rowIndex === 0) return 'font-medium ' }" to a table
- verify that the first row is bold

Chore/add way to apply css classes to the table based on column, row, row index, and/or column index

---

visualizations/frontend/charts/line_chart.html

Fix the default values for line "smoothing": 0 & "width": 0 to line "smoothing": 0.45 & "width": 1.5.
To test, this requires updates in both topcoat-public and topcoat-reports so check out in the 'fix/issue-summary-line-chart' topcoat-reports branch and run a build and sync modules.

Fix line smoothing & width

---

visualizations/frontend/other/TTable.vue

Currently if users want to sort a column in a table descending, then they have to wait for the it the data sorted ascending to come back before they can interact with the table again to sort descending. This adds a short debounce on the sorting data fetch so if users can quickly hit the sorting icon twice and not have to wait for an entire reload cycle.
I tested with a 250ms wait time and had issues clicking fast enough to get the second sort option, but no so fast that it just counted as a double click. 500 didn't cause a noticeable issue and was much easier to interact with. 
- In config.yml update the revision from main to `chore/add_debounce_to_sorting` and run sync and build.
- open the issues details page and sort a column by quickly single clicking the sorting icon twice.
- Verify …

Debounce table sorting

---

visualizations/frontend/other/TTable.vue

Used initially for Insights work, we will use this callback to post a message to the parent (AppUI Insights page), which will then display additional context to the user. Hopefully this is generic enough for some other use cases as well.
Example usage:
If specified, reports can make use of this:
```jsx
<TTable
:onCellClick="({cellValue, row, column, table}) => { /* I was clicked! */ }"
/>
```
- [Slack thread](https://snyk.slack.com/archives/C036EMLCZL4/p1677842109853269)
- [Jira ticket](https://snyksec.atlassian.net/browse/INST-287)

feat: add onCellClick to TTable

---

visualizations/frontend/charts/line_chart.html

Workaround to remove borders from linecharts. The borderless property used in the past is not working anymore. This will be re-done in the near future.
More context here: https://snyk.slack.com/archives/C02L4EW3KJS/p1681980485066819

fix: add border overwrite to line_chart

---

library/components/TTabs.vue

**What's new**
A new tab component for pages.
**Why use this instead of Snyk's**
We need a tab component that can support visualizations inside it's tab buttons along with label, snyk does not support that.
**Snytax**
```
<t-tabs
t-layer="tab_layer"
t-filter:tab="my_tab_url_parameter"
:tabs="[
{ label: "Tab one", slot: "section_1" }, 
{ label: "Tab two", slot: "section_2" }, 
]">
// By default tab buttons populate themselves, but to make any changes,
// their slot name can be used which prefixed with `tab_` so section_1 becomes `tab_section_one` 
// Tabs
<div slot="tab_section_one" slot-scope="{tab}">
{{ tab.label }}
</div>
// Sections
<div slot="section_1">
Tab one section 
</div>
<div slot="section_2">
Tab two section 
</div>
</t-tabs>
```
Note: `t-layer` file can just be a blank SQL …

tabs component

---

visualizations/frontend/other/TTable.vue

**Problem**
Plotly, when used inside tables does not reload with pagination, it always shows the result of first page.
**What's fixed**
Vue re-renders any div element if a `key` value is changed, which results in plotly re-adjusting itself to show new data.
**How to test**
1. Open https://snyk-insights.topcoatdata.app/reporting/a/develop.
2. Switch branch to `feat/enterprise_reporting`
3. Go to Analytics Page: https://snyk-insights.topcoatdata.app/reporting/analytics
4. There are a bunch of tables on this page along with tiny plotly charts used inside their rows.
5. Change pages of any table, plotly charts should change and not stay static.
**Before**
https://github.com/topcoat-data/topcoat-public/assets/43262405/3acea3bd-784f-4567-853b-80c871051715
**After** …

re-render plotly on pagination change

---

visualizations/frontend/filters/v2/TMultiSelector.vue

Allowing this component to react to changes to the filter value made from outside.
If there is a filter value set, then re-run the visualisation init. Also clears the checked array on init in case the new filter value is empty.

add onFiltersUpdated to TMultiSelector

---

visualizations/frontend/other/TTable.vue

This address a customer ask, that Ezra brought to the Frontend Platform team: https://snyk.slack.com/archives/C02L4EW3KJS/p1685517193204489
1. Makes entire column header clickable for triggering sort
2. removes `headerClasses` prop; did not seem to be used anywhere, and was not documented here: https://docs.google.com/document/d/1pwyyc1OtS6jUoOb3xNkFRFxPgnqJQFtmmptmtQ3D358/edit#
Go to https://snyk-insights.topcoatdata.app/
Change the branch in `config.yml` that points to topcoat-public to the branch name of this PR,as below:
```
modules:
revision: fix/sort-column-header-clickability
```
Save the config.yml file, and click the 'Build and Sync modules' button (it's a cloud symbol)
Refresh the reports in …

fix: make entire column header trigger sort

---

visualizations/frontend/other/TTable.vue

Users are confused when the table doesn't go into a loading state immediately after clicking the 'sort'. They get the imnpression nothing is happening. This PR puts the table into the loading state immediately, by moving the state change out of the debounced function. The network request is still debounced.
To test this fix...
Go to https://snyk-insights.topcoatdata.app/
Change the branch in `config.yml` that points to topcoat-public to the branch name of this PR,as below:
```
modules:
revision: fix/sort-loading-state
```
Save the config.yml file, and click the 'Build and Sync modules' button (it's a cloud symbol)
Refresh the reports in https://snyk-insights.topcoatdata.app/
Test the table column sort works. Make sure the …

fix: start loading immediately

---

visualizations/frontend/other/TTable.vue

@benbarnett picked up on an error with the TTable that was created with the removal of `headerClasses` in #239. See screenshots for the error
Go to https://snyk-insights.topcoatdata.app/
Change the branch in `config.yml` that points to topcoat-public to the branch name of this PR,as below:
```
modules:
revision: fix/headClasses-prop-still-being-referenced
```
Save the config.yml file, and click the 'Build and Sync modules' button (it's a cloud symbol)
Refresh the reports in https://snyk-insights.topcoatdata.app/
Test the table on Vulnerabilities Detail Report. Make sure it displays and each section you open is also displaying.
- [Slack thread](https://snyk.slack.com/archives/C036EMLCZL4/p1686749109465319)

fix: remove reference to headerClasses prop

---

visualizations/frontend/other/TTable.vue

Improves the TTable loading UX.
Addition:
- New prop: `height`. This will avoid the table jumps between no-data => data transitions.
- Pagination: the pagination component is not rendered until we have fetched the rows data.
On snyk-insights:
Use this module revision: `revision: feat/table-height`
Add some height to a table, for example in the issues-detail page, you can add a new prop to the table:
```js
<TTable 
height="993"
...
```
https://linear.app/snyk/issue/FP-913/topcoat-ttable-component-improvements
Before:
https://github.com/topcoat-data/topcoat-public/assets/1915140/79ca93c3-2026-44df-9bde-dafbe488f2dc
After:
https://github.com/topcoat-data/topcoat-public/assets/1915140/09a9566d-31cb-430a-a004-0583344a8554

feat: add prop for set custom height on TTable

---

visualizations/frontend/other/TTable.vue

Following on from #248, there was another edge case where if the table initially loads data, and then some combination of applied filters means that the table returns no results -- then the template columns were required again.
I've tested this with:
- **standard** tables that have initial data (and then applied a filter to produce an empty table again)
- this is the one that required this fix
- **standard** tables that have no initial data
- rendered as expected and as before
- **collapsable** tables that have initial data (and then applied a filter to produce an empty table again)
- rendered as expected and as before
- **collapsable** tables that have no initial data
- rendered as expected and as before
Screenshots for the states that had the layout issue shown below;
**Before (in …

fix: only add grid columns if collapsable has rows

---

visualizations/frontend/other/TTable.vue

`hight` was producing a collision with all the wrappers that topcoat-core adds automagically:
outerdiv, visualizationWrapper, etc.
So I had to rename the prop to defaultHeight instead.

fix: Rename height prop to defaultHeight

---

visualizations/frontend/other/TPdfTable.vue

In some cases, specific rows need to be customised from page, in that case this PR will expose `tr` tag to customise it from page file.
Will not affect current state of rows until exposed.

expose tr tags with slots in pdf table

---

visualizations/frontend/filters/TTagsSelector.vue

A feature requested by Kennan, in some cases we need a custom label to show up for values, with this prop default `value` name from sql layer will be replaced with provided text.
Sample: In this sample, default key name is replaced by `Custom label`.
**Testing: Fastest way to test**
- Inside IDE for snyk-insights, switch the main branch to `feat/project-collections` from GIT manager tab.
- Add this public branch to config.yml inside IDE and build modules.
- Inside another tab open this [url](https://snyk-insights.topcoatdata.app/reporting/issues-detail?context[org]=754984a6-a968-42b6-ae7c-bf8761451518) that has org id context for above filter. 
- Go to `pages/issues_detail.html` file and find the filter that is using `filter_project_collections` layer.
- Add the prop to t-tags-selector …

prop to override value label

---

library/components/TFormattedNumber.vue

This PR adds a component to format numbers in a consistent way. The intention is to centralise the logic for formatting numbers that lives in t-big-number, into a simple component. This will allow report authors to get consistent number formatting wherever they use this component. It will replace the logic in `t-big-number` in a separate PR.
This component will format the number to the 'en' locale until it reaches a threshold, and then it will be formatted using the 'compact' notation.
To test this component you can go follow the following steps
* Go to the `config.yml` file and replace the branch for topcoat-public with this branch name: 
```
modules:
revision: …
```

feat: create number formatting component

---

visualizations/frontend/other/TTable.vue

Table headers were attempting to sort the table (and failing), even when the sort option was not set. 
This PR fixes that by making rendering a button/attaching a click handler conditional.
To test this component:
* Go to the `config.yml` file and replace the branch for topcoat-public with this branch name: 
```
modules:
revision: fix/table-sort-condition
```
* Save the changes to the config.yml file and click `Build and Sync Modules` (the cloud icon) in the left hand menu
* Check tables across reports that have sorting on and sorting off.
* Ensure that tables without sorting do not attempt to sort on click of the header
* Ensure that sorting works as expected
- …

fix: do not sort table when sort is disabled.

---

visualizations/frontend/other/TTable.vue

Add margin-left to the first header cell to be aligned with the margin of the rows.
Use this branch `fix/table-headers-paddings` on any topcoat-insights branch to see the changes.
https://linear.app/snyk/issue/FP-1103/padding-of-table-headers-misaligned
|Before|After|
|---|---|
|<img width="633" alt="Screenshot 2023-07-27 at 17 55 39" src="https://github.com/topcoat-data/topcoat-public/assets/1915140/ef6e96fe-9680-454b-adbb-a64d011394a0">|<img width="1025" alt="Screenshot 2023-07-27 at 17 55 46" src="https://github.com/topcoat-data/topcoat-public/assets/1915140/f92f9b41-19da-4688-beae-db35c083f2cb">|
|<img width="766" alt="Screenshot 2023-07-27 at 17 54 25" src="https://github.com/topcoat-data/topcoat-public/assets/1915140/ed393df8-67af-48c1-b597-494b61b9be41">|<img width="786" …

fix: Add margin-left to the first header cell in TTable

---

visualizations/frontend/other/TBigNumber.vue
visualizations/frontend/other/TTabs.vue

This PR adds the hover styling to the tabs as per the following ticket
https://linear.app/snyk/issue/FP-1099/tab-nav-styling-hover-state
To test this component:
* Checkout the git branch for topcoat-reports that accompanies this change: https://github.com/snyk/topcoat-reports/pull/369
* Go to the `config.yml` file and replace the branch for topcoat-public with this branch name: 
```
modules:
revision: feat/tabs-hover-sytles
```
* Save the changes to the config.yml file and click `Build and Sync Modules` (the cloud icon) in the left hand menu
* Check that the hover styles closely resemble what is specified in the ticket
* Check big number across reports. Please report …

chore: implement tab hover states

---

library/components/TPdf.vue
library/components/TPdfDownloadHelper.vue

**Problem**
PDF Download fails on long pages, I came up with 2 fixes, one allows for increased timeout for ajax request while other replaces the backend's time.sleep(1) with axios interceptor that can track ongoing requests and signal the backend's selenium to capture the page when requests stop.
Interceptor will watch the layer requests that get fired every 250ms by frontend until layer gets the response.
1. t-pdf: Component will be able to handle ajax request's timeout from a prop (timeout=300).
2. t-pdf-download-helper: Will intercept axios to watch for layer requests, as soon as they stop it will show a component in DOM that selenium in backend will be watching for.
Instructions added to backend [PR](https://github.com/snyk/topcoat-core/pull/728), only for local testing.
- [Slack …

ajax request watcher and pdf component changes

---

visualizations/frontend/filters/v2/TMultiSelector.vue

This will introduce a breaking change. I'm thinking on a way to keep backwards compatibility.
Filters are going to be treated as array of string no matter the amount of filters. For example: ["one-value"] or ["one-value", "two-value", "n-value"].
This will avoid the special character used as a token to separate filters `|`.
Usually, that token is valid as a separator for query string parameters if your values are integers like ids for example. In our case, those values are arbitrary and controlled by our users. That's the reason that a label with a `|` on it was breaking the whole filtering experience.
This is a breaking change. It fixes a bug and it solves a Zendesk escalation but it changes the way that multi-value filters are managed by the TMultiSelector component. Before filters were …

fix: TMultiSelector filters as array

---

visualizations/frontend/filters/v2/TMultiSelector.vue

This will introduce a breaking change. I'm thinking on a way to keep backwards compatibility.
Filters are going to be treated as array of string no matter the amount of filters. For example: ["one-value"] or ["one-value", "two-value", "n-value"].
This will avoid the special character used as a token to separate filters `|`.
Usually, that token is valid as a separator for query string parameters if your values are integers like ids for example. In our case, those values are arbitrary and controlled by our users. That's the reason that a label with a `|` on it was breaking the whole filtering experience.
This is a breaking change. It fixes a bug and it solves a Zendesk escalation but it changes the way that multi-value filters are managed by the TMultiSelector component. Before filters were …

fix: TMultiSelector filters as array (#274)

---

visualizations/frontend/filters/v2/TMultiSelector.vue

This PR adds a `listMaxHeight` to the MultiSelect component.
The use case is, sometimes the filter is in a card which has a height restriction. When the height of the filter exceeds the card height, it causes weird UI effect.
Example UI issue see [thread](https://snyk.slack.com/archives/C03NR9J9P4Z/p1700754900841889)
With this prop we could then force the org filter not to exceed outer component height.

feat: add max height for multiselect dropdown

---

library/components/TNavigationDropdown.vue

Reset filters when the report is changed from the dropdown.
Once this PR is merged, we can update topcoat-reports with latest topcoat-core and topcoat-public to work on AppUI to use the new message sent by the children (iframed) page to AppUI.
1. Set this revision on the topcoat-reports config file on snyk-insights:
```code
revision: fix/report-page-changed
```
2. Build & Sync modules
3. Nothing should break or change since old reporting will do a full page reload between report page changes.
https://snyksec.atlassian.net/browse/FP-135

fix: Unset filters when report page changes

---

library/components/TCsvExport.vue
visualizations/frontend/other/TTable.vue

When there is not data, the CSV download process fails. In order to avoid this, we disable the button until there are results.
https://linear.app/snyk/issue/FP-1788/nosuchkey-displayed-when-downloading-csv-from-reports-page
Enabled:
Disabled:

fix: disable export to csv when there is not data
